package com.example.mapper.user;

import com.example.domain.user.UserLogin;
import com.example.domain.user.UserLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface UserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    int countByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    int deleteByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    int insert(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    int insertSelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    List<UserLogin> selectByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    UserLogin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserLogin record, @Param("example") UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    int updateByExample(@Param("record") UserLogin record, @Param("example") UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    int updateByPrimaryKeySelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    int updateByPrimaryKey(UserLogin record);
}