package com.example.domain.student;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Tue Sep 10 14:31:00 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbg.generated Tue Sep 10 14:31:00 CST 2019
     */
    private Long student_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbg.generated Tue Sep 10 14:31:00 CST 2019
     */
    private String student_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Tue Sep 10 14:31:00 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Tue Sep 10 14:31:00 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbg.generated Tue Sep 10 14:31:00 CST 2019
     */
    public Long getStudent_id() {
        return student_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param student_id the value for student.student_id
     *
     * @mbg.generated Tue Sep 10 14:31:00 CST 2019
     */
    public void setStudent_id(Long student_id) {
        this.student_id = student_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbg.generated Tue Sep 10 14:31:00 CST 2019
     */
    public String getStudent_name() {
        return student_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param student_name the value for student.student_name
     *
     * @mbg.generated Tue Sep 10 14:31:00 CST 2019
     */
    public void setStudent_name(String student_name) {
        this.student_name = student_name == null ? null : student_name.trim();
    }
}