package com.example.domain.user;

public class UserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.id
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.user_id
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.user_name
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.phone_num
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    private String phone_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.identity_card
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    private String identity_card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.description
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.id
     *
     * @return the value of t_user_login.id
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.id
     *
     * @param id the value for t_user_login.id
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.user_id
     *
     * @return the value of t_user_login.user_id
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.user_id
     *
     * @param user_id the value for t_user_login.user_id
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.user_name
     *
     * @return the value of t_user_login.user_name
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.user_name
     *
     * @param user_name the value for t_user_login.user_name
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.phone_num
     *
     * @return the value of t_user_login.phone_num
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public String getPhone_num() {
        return phone_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.phone_num
     *
     * @param phone_num the value for t_user_login.phone_num
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public void setPhone_num(String phone_num) {
        this.phone_num = phone_num == null ? null : phone_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.identity_card
     *
     * @return the value of t_user_login.identity_card
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public String getIdentity_card() {
        return identity_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.identity_card
     *
     * @param identity_card the value for t_user_login.identity_card
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public void setIdentity_card(String identity_card) {
        this.identity_card = identity_card == null ? null : identity_card.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.description
     *
     * @return the value of t_user_login.description
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.description
     *
     * @param description the value for t_user_login.description
     *
     * @mbggenerated Mon Sep 09 20:52:41 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}